# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WeatherOn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherOn
pod 'Alamofire', '~> 5.4'

  target 'WeatherOnTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'WeatherOnUITests' do
    # Pods for testing
  end

end
